spring.application.name=billing-service
server.port=${PORT:8083}


management.endpoints.web.exposure.include=health,info
logging.level.root=INFO


# Service URLs (Default to local, override in Cloud Run)
product.service.url=https://product-service-hesol3p2qa-as.a.run.app
vendor.service.url=https://vendor-service-hesol3p2qa-as.a.run.app
staff.service.url=https://staff-service-hesol3p2qa-as.a.run.app

# Firebase Configuration
firebase.credentials=classpath:serviceAccountKey.json
logging.level.com.Billing.Software.billing_service=DEBUG
logging.level.org.springframework.security=DEBUG
