spring.application.name=product-service
server.port=${PORT:8081}

# Firebase
firebase.bucket=raju--electronics.firebasestorage.app


google.application.credentials=classpath:serviceAccountKey.json

# Logging (for debugging)
logging.level.com.Billing.Software.product_service=DEBUG
logging.level.org.springframework.security=DEBUG
management.endpoints.web.exposure.include=health,info
logging.level.root=INFO
vendor.service.url=https://vendor-service-hesol3p2qa-as.a.run.app

